name: Build and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Environment
      run: |
        sudo apt-get install -y ncftp
    
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
        
    - name: Upload to FTP
      env:
        ftp_host: ${{ secrets.ftp_host }} 
        ftp_username: ${{ secrets.ftp_username }}
        ftp_password: ${{ secrets.ftp_password }}
        ftp_path: ${{ secrets.ftp_path }}    
      run: |
        ncftpput -Rzv -u "$ftp_username" -p "$ftp_password" $ftp_host $ftp_path ${{ github.workspace }}/_site/*
